[alias]
b = "build"
br = "build --release"
c = "check"
t = "test"
fixit = "fix --workspace --all-features --benches --examples --tests --allow-dirty --allow-staged"

t-all = "test --all-features"
bb-all = "bench -q --all-features"

ci-clippy = "clippy --workspace --all-features --benches --examples --tests -- -D warnings"
ci-fmt = "fmt --check"
ci-doc = "doc --workspace --all-features --no-deps"

[env]
DIVAN_BYTES_FORMAT = "binary"
DIVAN_SAMPLE_SIZE = "1000"
DIVAN_SAMPLE_COUNT = "1000"

[target.'cfg(all())']
rustflags = [
    "-Wclippy::all",
    "-Wrust_2018_idioms",
]
