[alias]
b = "build"
br = "build --release"
c = "check"
t = "test"
fixit = "fix --benches --examples --tests --all-features --allow-dirty --allow-staged"

t-all = "test --all-features"
bb-all = "bench -q --all-features"

[env]
DIVAN_BYTES_FORMAT = "binary"
DIVAN_SAMPLE_SIZE = "1000"
DIVAN_SAMPLE_COUNT = "1000"

[target.'cfg(all())']
rustflags = [
    "-Wclippy::all",
    "-Wrust_2018_idioms",
]
